# Generated by Django 4.1.4 on 2023-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
